### ISSUE TITLE
gl3w build 403 error

### ISSUE THREAD

**Issue by iscas-zac** [KTStephano/StratusGFX#29]
[gl3w has merged a PR](https://github.com/skaslev/gl3w/commit/5f8d7fd191ba22ff2b60c1106d7135bb9a335533), which helps downloading the files. Maybe you can update the dependency?

**Comment by iscas-zac** [comment]
By the way, it's really a pain to build this project by hand. Cmake always complains about SDL and assimp. I don't know if I'm going a wrong way.

**Comment by KTStephano** [comment]
> By the way, it's really a pain to build this project by hand. Cmake always complains about SDL and assimp. I don't know if I'm going a wrong way.

Let me see if I can work out an easier way to build it from the beginning. The only dependency that will probably be a bit weird either way is SDL.

**Comment by iscas-zac** [comment]
Great! By the way, I never would know SDL and Cmake can interact so badly before cloning this repo :)

**Comment by KTStephano** [comment]
The build system has been updated and the readme has new instructions. Hopefully they are a bit smoother now. You will still have to download SDL from their site so hopefully you find a way to get it to play nicely with CMake. Let me know!

**Comment by KTStephano** [comment]
For the build SDL2 has been added to the build steps

**Comment by iscas-zac** [comment]
Hello, I pulled the new repo and tried again, and stuck in this:

> Build and rest of the third party libraries -> should only need to do this once per clone
>```
>cmake --build . -j 8 --config RelWithDebInfo
>```
 
and get "Error: could not load cache"

I personally think this folder is missing a cmake txt file.

By the way, I think the build commands in README can be wrote into a script to be convenient.

***

To be complete: before that error, the `cmake .. -DDEPENDENCY_BUILD=ON -DBUILD_TESTING=OFF` command gave me this:
> -- Shared libraries enabled
-- compiling zlib from sources
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - failed
-- Looking for fseeko
-- Looking for fseeko - not found
-- Looking for unistd.h
-- Looking for unistd.h - not found
-- Enabled importer formats: AMF 3DS AC ASE ASSBIN B3D BVH COLLADA DXF CSM HMP IRRMESH IQM IRR LWO LWS M3D MD2 MD3 MD5 MDC MDL NFF NDO OFF OBJ OGRE OPENGEX PLY MS3D COB BLEND IFC XGL FBX Q3D Q3BSP RAW SIB SMD STL TERRAGEN 3D X X3D GLTF 3MF MMD
-- Disabled importer formats:
-- Enabled exporter formats: OBJ OPENGEX PLY 3DS ASSBIN ASSXML M3D COLLADA FBX STL X X3D GLTF 3MF PBRT ASSJSON STEP
-- Disabled exporter formats:
-- Treating all warnings as errors (for assimp library only)
-- Configuring done (8.3s)
-- Generating done (0.2s)
CMake Warning:
  Manually-specified variables were not used by the project:
    BUILD_TESTING
-- Build files have been written to: ~/StratusGFX

**Comment by KTStephano** [comment]
Yeah you're right, moving the 3rd party dependencies to a script is going to be necessary. I'm working on that now.

When you ran `cmake --build . -j 8 --config RelWithDebInfo` were you inside the StratusGFX/ThirdParty directory?

**Comment by iscas-zac** [comment]
> Yeah you're right, moving the 3rd party dependencies to a script is going to be necessary. I'm working on that now.
> 
> When you ran `cmake --build . -j 8 --config RelWithDebInfo` were you inside the StratusGFX/ThirdParty directory?

Yes.

**Comment by KTStephano** [comment]
Master branch has been updated again with new build steps. Third party dependencies have been wrapped into `dependency_build.py` so the only pure cmake step is for the StratusGFX source. Let me know if it works!

**Comment by iscas-zac** [comment]
Great, it builds after cloning from scratch. I think I must have messed up the cmake files and 'cmake ..' simply won't output to the current (build) folder.

My building computer has a very low graphic card and encounters some shader errors for now. I'm going to update the drivers and see if the binary will run then. Or maybe I can run it from another computer.

Thanks for helping!

**Comment by KTStephano** [comment]
Awesome, glad it worked! I'm interested to hear how it goes for you running on either computer you have. I've only been able to test it on my one machine so I don't know how things will go on other hardware.

I'll go ahead and close this issue but feel free to open up others once you can start testing things.
