### ISSUE TITLE
Incorrect link to Crytek Sponza

### ISSUE THREAD

**Issue by InsightGit** [KTStephano/StratusGFX#82]
Hey!

Great work on your engine! While I was getting ready to build it in order to debug my own, I noticed that in the credits section of your README the Crytek Sponza link doesn't point to a model page with the Crytek Sponza model but instead a link to your abandoned warehouse model.

**Comment by KTStephano** [comment]
Oh yeah, thanks for catching that! I just added a fix

**Comment by InsightGit** [comment]
No worries! Thanks for open sourcing your engine for others to learn from! Really appreciate it!

**Comment by KTStephano** [comment]
Yeah no problem!
